const Product = require('../models/product');
const {authToken,authAccount} = require('../middleware/auth');
const express = require('express');
const router = express.Router();
const productController = require('../controller/product');
router.get('/product',productController.getProduct);
router.post('/product',authToken,authAccount(['USER']),productController.postProduct);
router.patch('/product/:id',authToken,authAccount(['USER','ADMIN']),productController.patchProduct);
router.delete('/product/:id',authToken,authAccount(['USER','ADMIN']),productController.deleteProduct);
module.exports = router;
